spring:
  application:
    name:multi-db
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/mdb_user
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/mdb_product
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
